### ISSUE TITLE
CuDNN version

### ISSUE THREAD

**Issue by yxu0611** [charlyng/Embedded-Deep-Learning#1]
Hi,  

It is a good benchmark.

Could you share us what is the CuDNN vesion do you use?

And also, can you complete the GPU Utilization average for TitanX?

Thank you very much.

**Comment by charlyng** [comment]
Hi @yxu0611,

I am using CuDNN 4 for the benchmarking and have updated the tables in Readme.md.

Thank you.

**Comment by weishengchong** [comment]
Charlyn,
Nvidia's caffe fp16 is updated, we will
Diff its cpp with previous fp16
Run it in tx1, see can solve clash problem or not
Thi a is after we finish prepar e demo

Benchmarking branch experimental/fp16 crashes for large batch sizes on the
TX1 (#137)
To: "NVIDIA/caffe" <caffe@noreply.github.com>
Cc: "Chong" <ws.chong.sg@gmail.com>, "Comment" <comment@noreply.github.com>

Could you try https://github.com/drnikolaev/caffe/tree/caffe-0.14-fp16
please? It's much newer (still very experimental though).
On 26 Apr 2016 13:35, "charlyng" <notifications@github.com> wrote:

Hi @yxu0611 <https://github.com/yxu0611>,

I am using CuDNN 4 for the benchmarking and have updated the tables in
Readme.md.

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/charlyng/Embedded-Deep-Learning/issues/1#issuecomment-214620823>

**Comment by weishengchong** [comment]
http://forum.notebookreview.com/threads/fix-for-slow-boot-issue-of-asus-x-99-motherboards.781301/

On Thu, Apr 28, 2016 at 6:18 AM, Ws CHONG <ws.chong.sg@gmail.com> wrote:

> Charlyn,
> Nvidia's caffe fp16 is updated, we will
> Diff its cpp with previous fp16
> Run it in tx1, see can solve clash problem or not
> Thi a is after we finish prepar e demo
>
> Benchmarking branch experimental/fp16 crashes for large batch sizes on the
> TX1 (#137)
> To: "NVIDIA/caffe" <caffe@noreply.github.com>
> Cc: "Chong" <ws.chong.sg@gmail.com>, "Comment" <comment@noreply.github.com
> >
>
> Could you try https://github.com/drnikolaev/caffe/tree/caffe-0.14-fp16
> please? It's much newer (still very experimental though).
> On 26 Apr 2016 13:35, "charlyng" <notifications@github.com> wrote:
>
> Hi @yxu0611 <https://github.com/yxu0611>,
>
> I am using CuDNN 4 for the benchmarking and have updated the tables in
> Readme.md.
>
> Thank you.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/charlyng/Embedded-Deep-Learning/issues/1#issuecomment-214620823>
>
>


-- 
Regards,
CHONG Wei Sheng
Tel +65-9008-4478
ws.chong.sg@gmail.com
